site_name: Shaun's Documentation
site_url: https://vaughnshaun.github.io/documentation
repo_url: https://github.com/vaughnshaun/documentation
copyright: Shaun Vaughn
theme:
  name: 'material'
  palette:
    primary: amber
    accent: "deep orange"
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
markdown_extensions:
  - attr_list
nav:
  - Home:
    - Welcome: index.md
  - Azure: 
    - Overview: azure/overview.md
    - Certifications:
      - Az-900:
        - Overview: azure/certifications/az-900/overview.md
        - Cloud Concepts: 
          - Overview: azure/certifications/az-900/cloud-concepts/overview.md
          - Cloud Computing: azure/certifications/az-900/cloud-concepts/cloud-computing.md
        - Glossary: azure/certifications/az-900/glossary.md
      - Az-104:
        - Overview: azure/certifications/az-104/overview.md